# Generated by Django 5.0.6 on 2026-05-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='URL')),
                ('kind', models.CharField(choices=[('anime', 'Аниме'), ('manga', 'Манга'), ('other', 'Другое')], default='anime', max_length=20, verbose_name='Тип')),
                ('original_name', models.CharField(blank=True, max_length=220, verbose_name='Оригинальное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('poster_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к постеру в медиатеке')),
                ('gallery_folder', models.CharField(blank=True, max_length=500, verbose_name='Папка галереи тайтла')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Имя')),
                ('slug', models.SlugField(blank=True, max_length=240, verbose_name='URL')),
                ('gender', models.CharField(choices=[('female', 'Женский'), ('male', 'Мужской'), ('other', 'Другое')], default='female', max_length=20, verbose_name='Пол')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='Роль')),
                ('race', models.CharField(blank=True, max_length=160, verbose_name='Раса')),
                ('body', models.TextField(blank=True, verbose_name='Характеристики тела')),
                ('features', models.TextField(blank=True, verbose_name='Особенности')),
                ('abilities', models.TextField(blank=True, verbose_name='Способности')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('gallery_folder', models.CharField(blank=True, max_length=500, verbose_name='Папка галереи персонажа')),
                ('portrait_path', models.CharField(blank=True, max_length=500, verbose_name='Портрет в медиатеке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='photos.title')),
            ],
            options={
                'ordering': ['gender', 'name'],
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
