# Generated by Django 5.0.6 on 2026-05-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bust',
            field=models.CharField(blank=True, max_length=80, verbose_name='Грудь'),
        ),
        migrations.AddField(
            model_name='character',
            name='eye_color',
            field=models.CharField(blank=True, max_length=120, verbose_name='Цвет глаз'),
        ),
        migrations.AddField(
            model_name='character',
            name='hair_color',
            field=models.CharField(blank=True, max_length=120, verbose_name='Цвет волос'),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.CharField(blank=True, max_length=80, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='character',
            name='hips',
            field=models.CharField(blank=True, max_length=80, verbose_name='Бёдра'),
        ),
        migrations.AddField(
            model_name='character',
            name='waist',
            field=models.CharField(blank=True, max_length=80, verbose_name='Талия'),
        ),
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.CharField(blank=True, max_length=80, verbose_name='Вес'),
        ),
    ]
