# Generated by Django 5.0.6 on 2026-05-23 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_character_bust_character_eye_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('color', models.CharField(default='#1f7a6d', max_length=24, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task', 'Задача'), ('reminder', 'Напоминание'), ('note', 'Заметка'), ('record', 'Запись')], default='task', max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=220, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('tags', models.CharField(blank=True, max_length=240, verbose_name='Метки')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='photos.todoproject')),
            ],
            options={
                'ordering': ['is_done', '-is_pinned', 'due_at', '-created_at'],
            },
        ),
    ]
