# Generated by Django 5.0.6 on 2026-05-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_todoproject_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='18+'),
        ),
        migrations.AlterField(
            model_name='title',
            name='kind',
            field=models.CharField(choices=[('anime', 'Аниме'), ('manga', 'Манга'), ('game', 'Игры'), ('hentai', 'Хентай'), ('movie', 'Кино'), ('book', 'Книги'), ('other', 'Другое')], default='anime', max_length=20, verbose_name='Тип'),
        ),
    ]
