# Generated by Django 5.0.6 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0005_textdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Завершено"),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Низкий"),
                    ("medium", "Средний"),
                    ("high", "Высокий"),
                    ("urgent", "Срочно"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Приоритет",
            ),
        ),
    ]
