# Generated by Django 5.0.6 on 2026-08-01 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_title_catalog_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='Отображаемое имя')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='Город или страна')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('avatar_path', models.CharField(blank=True, max_length=500, verbose_name='Аватар в медиатеке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
