# Generated by Django 5.0.6 on 2026-08-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='encrypted_body',
            field=models.TextField(blank=True, verbose_name='Зашифрованный текст'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='is_encrypted',
            field=models.BooleanField(default=False, verbose_name='Зашифрована'),
        ),
    ]
