# Generated by Django 5.0.6 on 2026-08-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_todoitem_encrypted_body_todoitem_is_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.CharField(blank=True, max_length=160, verbose_name='Фракция'),
        ),
    ]
